### PR TITLE
Feature/create connection wrapper

### PR DESCRIPTION
**Pull request by nebojsa-lalic-devtech**
- Adding **Connection Wrapper** For **MySQL & MongoDB**

- Should not affect the rest of the code

- Have two temporary methods in "public/index.php" for testing connections

- Test should start in "app/NL/database/Config.php" class, with changing current database name.

- Routes:

1. "http://localhost:8000/mongodb" - post method
2. "http://localhost:8000/mysql" - post method

### CODE REVIEW

**Comment by dejan-babic** [comment]
Some changes I'd like to see

1. Database Wrapper should have a constructor, and you should pass the Config object to it.
2. Make sure you sort the function visibility right r.g. the getDatabaseConnection should be public, the other two are always private.
3. The Database wrapper started off good, but you could easily run into trouble, look at this example
http://coderoncode.com/php/programming/design/patterns/coding/2015/01/25/design-patterns-in-php-adapters.html, it can be very helpful.
4. PSR brakets mostly.

**Comment by nebojsa-lalic-devtech** [comment]
I'm not sure if the constructor like this should be in Database class or is better option do this in the constructor of Config class, so that the Database class inherits its constructor?

**Comment by dejan-babic** [comment]
1st and 3rd points were not addressed at all.

Please read the article with the adapter pattern I provided in the 3rd point and think of NotificationManager in the example as your Database class and make the corrections. We want do do so, so we can have a MongoAdapter and MysqlAdapter, and this will allow us to have any future XXXAdapter.
You can than utilize the class in the bootstrap for example.

You want to avoid tight coupling like you have in your Database class where you directly instantiate the Config file. The simplest way to fix this is to use constructor injection e.g. new Database(new Config());
Yuo will see how this fits in to your code.

**Comment by nebojsa-lalic-devtech** [comment]
@dejan-babic  I made many varieties of this connection wrapper, but this looks clearest to me, with added 'Connection Adapters' so we later can add more databases easily. How does this look to you ?

**Comment by dejan-babic** [comment]
@nebojsa-lalic-devtech 
Looking better, but still you need to improve the code.
1. You are not using the config values any more in the adapters, you build the connection with hc values.
2. The adapter interface should hold one more method e.g. execute to cover the (query or executeBulkWrite variants)
3. In the Database class switch case, no need to store the var in self::connection, you can just return it directly
4. Still missing phpdoc on most of function calls classes.

**Comment by nebojsa-lalic-devtech** [comment]
@dejan-babic  I hope that everything is implemented as it was necessary

**Pull request merged**
