### PR TITLE
CRUD MySQL

### PR DESCRIPTION
**Pull request by nebojsa-lalic-devtech**
# What's the purpose of this MR?

Add CRUD operations with MySQL database

# Impact Analysis

/

# Where should the tester start?

Tester should start from Database class ... then go level up in EmployeeService class, and Validation class, and in the end in 'public/index.php'

# How should this be manually tested?

/

# Any background context you want to provide?

/

# What are the relevant tickets?

Simple App - CRUD with MySQL

# Screenshots (if appropriate)

(N/A)

### CODE REVIEW

**Comment by dejan-babic** [comment]
@nebojsa-lalic-devtech 
You need to update this branch with develop before we continue.

**Comment by nebojsa-lalic-devtech** [comment]
@dejan-babic this branch is updated with develop branch, now is without conflicts

**Comment by nebojsa-lalic-devtech** [comment]
@dejan-babic last commit is just one small update for merge feature with develop branch

**Comment by dejan-babic** [comment]
Like I said in the previous PR 

"You want to avoid tight coupling like you have in your Database class where you directly instantiate the Config file. The simplest way to fix this is to use constructor injection e.g. new Database(new Config());
Yuo will see how this fits in to your code."

You have a couple of places in your code where you instantiate a class in a constructor (e.g. Database in the Validation etc.)
Try to identify those places and as I said, as a minimum use constructor injection to avoid coupling like that.

**Comment by nebojsa-lalic-devtech** [comment]
@dejan-babic I had a misunderstanding about dependency injection, so now I hope code looks better.

**Pull request merged**
